- type: replace
  path: /releases/-
  value:
    name: routing # https://github.com/cloudfoundry/routing-release/releases
    version: 0.175.0
    url: https://bosh.io/d/github.com/cloudfoundry-incubator/cf-routing-release?v=0.175.0
    sha1: 1bfacc14a58489b0a5761d0ea084eddace77ce3034c10f4a3db1db78ed4716b8

- type: replace
  path: /instance_groups/name=rmq/jobs/-
  value:
    name: route_registrar
    release: routing
    consumes:
      nats:
        from: nats
        deployment: ((cf_deployment))
    properties:
      route_registrar:
        routes:
        - name: rabbitmq_management-((bosh_deployment))
          uris:
          - ((bosh_deployment)).((cf_apps_domain))
          port: 15672
          registration_interval: 10s
          health_check:
            name: rabbitmq_management-((bosh_deployment))
            script_path: /var/vcap/jobs/rabbitmq-server/bin/rabbitmq_management_http_ok
        - name: netdata-((bosh_deployment))
          uris:
          - netdata-((bosh_deployment)).((cf_apps_domain))
          port: 19999
          registration_interval: 10s
          health_check:
            name: netdata-((bosh_deployment))
            script_path: /var/vcap/jobs/netdata/bin/netdata_http_ok
          prepend_instance_index: true
