- type: replace
  path: /releases/-
  value:
    name: "bpm"
    version: "0.10.0" # https://bosh.io/releases/github.com/cloudfoundry-incubator/bpm-release?all=1
    url: "https://bosh.io/d/github.com/cloudfoundry-incubator/bpm-release?v=0.10.0"
    sha1: "f6140862d763ba397e7d8675fbb56020d4148081"

- type: replace
  path: /releases/-
  value:
    name: "routing" # http://bosh.io/releases/github.com/cloudfoundry-incubator/cf-routing-release?all=1
    version: "0.180.0"
    url: "https://bosh.io/d/github.com/cloudfoundry-incubator/cf-routing-release?v=0.180.0"
    sha1: "990c2c319e6063573eec18dbeb7c3631a382db7d"

- type: replace
  path: /instance_groups/name=rmq/jobs/-
  value:
    name: bpm
    release: bpm

- type: replace
  path: /instance_groups/name=rmq/jobs/-
  value:
    name: route_registrar
    release: routing
    consumes:
      nats:
        from: nats
        deployment: ((cf_deployment))
    properties:
      route_registrar:
        routes:
        - name: rabbitmq_management-((bosh_deployment))
          uris:
          - ((bosh_deployment)).((cf_apps_domain))
          port: 15672
          registration_interval: 10s
          health_check:
            name: rabbitmq_management-((bosh_deployment))
            script_path: /var/vcap/jobs/rabbitmq-server/bin/rabbitmq_management_http_ok
        - name: netdata-((bosh_deployment))
          uris:
          - netdata-((bosh_deployment)).((cf_apps_domain))
          port: 19999
          registration_interval: 10s
          health_check:
            name: netdata-((bosh_deployment))
            script_path: /var/vcap/jobs/netdata/bin/netdata_http_ok
          prepend_instance_index: true
