- type: replace
  path: /releases/-
  value:
    name: routing # https://github.com/cloudfoundry/routing-release/releases
    version: 0.176.0
    url: https://bosh.io/d/github.com/cloudfoundry-incubator/cf-routing-release?v=0.176.0
    sha1: fcd49af96983bedcb7498d3f291c8cc1e977933358a27ef44e3143f7b1e3ecde

- type: replace
  path: /instance_groups/name=rmq/jobs/-
  value:
    name: route_registrar
    release: routing
    consumes:
      nats:
        from: nats
        deployment: ((cf_deployment))
    properties:
      route_registrar:
        routes:
        - name: rabbitmq_management-((bosh_deployment))
          uris:
          - ((bosh_deployment)).((cf_apps_domain))
          port: 15672
          registration_interval: 10s
          health_check:
            name: rabbitmq_management-((bosh_deployment))
            script_path: /var/vcap/jobs/rabbitmq-server/bin/rabbitmq_management_http_ok
        - name: netdata-((bosh_deployment))
          uris:
          - netdata-((bosh_deployment)).((cf_apps_domain))
          port: 19999
          registration_interval: 10s
          health_check:
            name: netdata-((bosh_deployment))
            script_path: /var/vcap/jobs/netdata/bin/netdata_http_ok
          prepend_instance_index: true
